name: workflow

on:
  push:
    branches :
        main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Resolve dependencies
      run: ./mvnw -f ./pom.xml dependency:resolve 

    - name: Build with Maven
      run: ./mvnw -f ./pom.xml clean install

    - name: Run unit tests
      run: ./back-end/mvnw -f back-end/pom.xml test
